FROM nginx:stable-alpine

RUN mkdir -p /usr/share/nginx/html/app/deals

COPY ./dist /usr/share/nginx/html/app/deals

RUN echo 'server { \
    listen 80; \
    location /app/deals/ { \
        root /usr/share/nginx/html; \
        try_files $uri $uri/ /app/deals/index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf
